### PR TITLE
enabling centos-9-stream-x86_64 for PR CI

### PR DESCRIPTION
**Pull request by kkaarreell**

### CODE REVIEW

**Comment by thrix** [comment]
CentOS Stream 9 should now work, trying to verify on this PR

**Comment by thrix** [comment]
this luks butter, now we need to solve the beakerlib problem for CentOS 9 ... https://issues.redhat.com/browse/TFT-838

**Comment by kkaarreell** [comment]
Thank you @thrix , the last test failure is expected, this is a regression in tpm2-tools.

**Comment by thrix** [comment]
@kkaarreell how cool! a regression found \o/

**Comment by kkaarreell** [comment]
> @kkaarreell how cool! a regression found \o/

Well, it is already known one.

**Pull request merged**
