### PR TITLE
Make --install a default in limeCopyKeylimeFile

### PR DESCRIPTION
**Pull request by kkaarreell**

### CODE REVIEW

**Comment by kkaarreell** [comment]
@Koncpa I have noticed that we are not shipping `create_mb_refstate` script and therefore I left existing tests untouched.

**Comment by kkaarreell** [comment]
> @Koncpa I have noticed that we are not shipping `create_mb_refstate` script and therefore I left existing tests untouched.

Update, wit ship it in `/usr/share/keylime` but upstream installation script does not install it. Maybe we should modify our keylime install task to copy it to /usr/share/keylime so we can always find it there. WDYT?

**Comment by Koncpa** [comment]
> > @Koncpa I have noticed that we are not shipping `create_mb_refstate` script and therefore I left existing tests untouched.
> 
> Update, wit ship it in `/usr/share/keylime` but upstream installation script does not install it. Maybe we should modify our keylime install task to copy it to /usr/share/keylime so we can always find it there. WDYT?

Yeah, sure...will be the most simple. Do you will implement it in this PR?

**Review by Koncpa — APPROVED** [review]

**Comment by kkaarreell** [comment]
> Yeah, sure @kkaarreell ...it will be the most simple. Do you will implement it in this PR?

Yes, I have just pushed an update.

**Pull request merged**
