### PR TITLE
Add /update/basic-attestation-on-localhost/all to the right plan

### PR DESCRIPTION
**Pull request by kkaarreell**

### CODE REVIEW

**Review by Koncpa — APPROVED** [review]

**Comment by kkaarreell** [comment]
Only commit [Add /update/basic-attestation-on-localhost/all to the right plan](https://github.com/RedHat-SP-Security/keylime-tests/pull/295/commits/ab7b17fb69491bc9bb58378936d8828aefc71c45) has been backported to rhel-9-main

**Pull request merged**
