### PR TITLE
WIP: Test scenario checking using multiple revocation scripts

### PR DESCRIPTION
**Pull request by Koncpa**
Scenario check running multiple revocation scripts via
multiple options how to run.

#180

### CODE REVIEW

**Comment by Koncpa** [comment]
I found out issue with specifying revocation script in keylime conf.

[ISSUE](https://github.com/keylime/keylime/issues/1095)

**Comment by Koncpa** [comment]
This is now blocked by the missing fix for the actual keylime issue.

**Comment by Koncpa** [comment]
> @Koncpa Do you know is this is still blocked on upstream fix?

The problem I opened in the upstream is still unresolved.

**Comment by ansasaki** [comment]
Hi, the support for lists in `revocation_actions` option was introduced in https://github.com/keylime/rust-keylime/pull/604

The previous created issue for the python agent is no longer relevant, but I think this test can be used for the rust agent.

**Pull request closed without merging**
