### PR TITLE
[WIP] Enable code coverage measuring for keylime services

### PR DESCRIPTION
**Pull request by kkaarreell**
Starts keylime services via "coverage run" when COVERAGE environment variable is defined and non-empty.
This enable gathering code coverage metrics.

### CODE REVIEW

**Comment by kkaarreell** [comment]
Requires coverage script to be available by doing "pip3 install coverage". I think we can implement another setup task to do the required setup.
Eventually, I am considering to replace COVERAGE env variable with a dedicated file storing coverage script parameters (stored by the setup task) so that usage of coverage script is auto detected. This will be probably subject of future update, for now I would just want to get some feedback.

**Comment by kkaarreell** [comment]
Currently we run keylime_tenant via expect (since entering a password/key is necessary) and therefore running it via coverage script would be a bit more tricky.

**Comment by kkaarreell** [comment]
> Currently we run keylime_tenant via expect (since entering a password/key is necessary) and therefore running it via coverage script would be a bit more tricky.

This is addressed in the new commit by introducing `lime_keylime_tenant` wrapper.

**Review by sopos — APPROVED** [review]
It seems to me reasonable. I would like to see also the report interpretation, tough.

LGTM

**Comment by kkaarreell** [comment]
> It seems to me reasonable. I would like to see also the report interpretation, tough.

@sopos I have added `setup/generate_coverage_report` task.

**Comment by sopos** [comment]
Can we also update plans/keylime-tests-github-ci.fmf to see the results in the CI?

**Comment by kkaarreell** [comment]
> Can we also update plans/keylime-tests-github-ci.fmf to see the results in the CI?

I am not sure it would be helpful. We would see only overall coverage per file but I am not able to attached the HTML report (or an archive of it).

**Comment by kkaarreell** [comment]
> > Can we also update plans/keylime-tests-github-ci.fmf to see the results in the CI?
> 
> I am not sure it would be helpful. We would see only overall coverage per file but I am not able to attached the HTML report (or an archive of it).

I will enable it for this tests repo so we can see that it is working with future test updates.
https://github.com/RedHat-SP-Security/keylime-tests/pull/22

**Pull request merged**
