### PR TITLE
Use non-default cryptographic algorithm

### PR DESCRIPTION
**Pull request by Koncpa**
New setup task adding enviroment variable
which allow to set non-default algorithm in basic localhost test.

### CODE REVIEW

**Comment by kkaarreell** [comment]
@Koncpa Do you know if this is still blocked on upstream?

**Comment by Koncpa** [comment]
> @Koncpa Do you know if this is still blocked on upstream?

I created [bugzilla ticket](https://bugzilla.redhat.com/show_bug.cgi?id=2110456) related to this PR, which is still unresolved.

**Comment by kkaarreell** [comment]
> > @Koncpa Do you know if this is still blocked on upstream?
> 
> I created [bugzilla ticket](https://bugzilla.redhat.com/show_bug.cgi?id=2110456) related to this PR, which is still unresolved.

If the issue is relevant for upstream keylime please file also an issue in upstream (and link it to bugzilla one).

**Comment by Koncpa** [comment]
As python agent will be deprecated, I linked this issue on keylime rust upstream : [ISSUE](https://github.com/keylime/rust-keylime/issues/513)

**Pull request closed without merging**
