### PR TITLE
New test tpm-issuer-cert-using-ecc

### PR DESCRIPTION
**Pull request by kkaarreell**
This is a reproducer for
https://github.com/keylime/keylime/issues/1070

### CODE REVIEW

**Comment by kkaarreell** [comment]
ATM I am not able to reproduce the reported issue, most likely the TPM setup is not correct.

**Comment by kkaarreell** [comment]
Test is not failing as expected. From `keylime_tenant` I am getting
```
# keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -u d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --verify --allowlist allowlist.txt --exclude excludelist.txt -f excludelist.txt -c add
Reading configuration from ['/etc/keylime.conf']
2022-08-19 20:03:31.424 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.2
2022-08-19 20:03:31.426 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2022-08-19 20:03:31.426 - keylime.registrar_client - WARNING - TLS is enabled.
2022-08-19 20:03:31.426 - keylime.registrar_client - INFO - Setting up client TLS...
2022-08-19 20:03:31.444 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
<Response [200]>
2022-08-19 20:03:31.529 - keylime.tpm - WARNING - PCR #0 in quote not found in tpm_policy, skipping.
2022-08-19 20:03:31.529 - keylime.tpm - ERROR - No Root CA matched EK Certificate
2022-08-19 20:03:31.529 - keylime.tenant - WARNING - Invalid EK certificate
2022-08-19 20:03:31.529 - keylime.tenant - ERROR - TPM Quote from cloud agent is invalid for nonce: CGGi8819iBBFg1ytEHVP
```
There is nothing suspicious in service logs.

When extracting the EK cert manually I can verify that it is correct.
```
# tpm2_nvread 0x1c00002 > ekcert-rsa.der
WARN: Reading full size of the NV index
# openssl x509 -inform der -in ekcert-rsa.der -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 5 (0x5)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = TPM cert issuer
        Validity
            Not Before: Aug 19 19:59:56 2022 GMT
            Not After : Dec 31 23:59:59 9999 GMT
        Subject: CN = unknown
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:a4:29:8d:52:63:ed:b2:ea:e7:b4:95:1b:46:a7:
                    ef:5f:a5:9c:6a:ab:36:d7:f1:b8:14:c6:23:fa:da:
                    64:d7:a1:5c:1a:46:8c:37:c3:e0:87:f9:cb:7f:48:
                    14:63:13:5a:74:35:fd:d2:38:b4:b8:75:25:69:93:
                    8d:b8:34:a8:80:ac:57:c8:d7:0d:b0:d2:4b:93:eb:
                    63:93:29:0a:99:29:bf:9e:c3:88:4f:ff:db:d9:7d:
                    73:9c:11:99:30:1f:39:a4:fc:0d:52:68:0f:01:fc:
                    31:6c:7f:8e:d7:60:0e:da:e2:f8:8c:b3:0d:28:8d:
                    54:4f:aa:38:00:34:86:58:12:88:9a:06:7e:3d:40:
                    1b:f2:88:63:64:bc:15:cb:e6:92:c9:c4:a4:9f:24:
                    17:80:ad:d3:c0:64:f0:7f:d0:a9:3d:02:88:16:e7:
                    61:f0:b7:58:3b:d8:9d:61:42:45:4b:a6:fc:8b:f0:
                    59:9e:34:29:b6:86:f8:a5:75:36:6b:05:39:64:92:
                    88:ac:ad:f1:55:f9:3a:89:d8:8e:27:cb:ac:50:d9:
                    2c:2d:eb:74:61:e3:27:3f:84:46:59:7b:50:56:92:
                    e5:44:8f:2e:a9:f1:13:f3:43:cc:a5:f7:e4:3e:01:
                    c6:4b:0c:fd:55:96:0b:c2:54:8f:12:0f:b3:41:d7:
                    19:af
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Extended Key Usage: 
                2.23.133.8.1
            X509v3 Subject Alternative Name: critical
                DirName:/2.23.133.2.1=id:00001014/2.23.133.2.2=swtpm/2.23.133.2.3=id:20191023
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Directory Attributes: 
                0.0...g....1.0...2.0.......
            X509v3 Authority Key Identifier: 
                keyid:AA:E6:28:A5:D4:DC:44:52:C9:E1:16:3C:47:9E:D7:52:BA:35:84:38

            X509v3 Key Usage: critical
                Key Encipherment
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:8b:d8:5c:58:2b:0e:10:c6:9a:b3:0f:d2:98:
         35:bf:a7:ef:71:d8:04:88:8a:58:f6:ed:81:0c:c1:3e:82:2f:
         9d:02:21:00:a8:ca:1c:c9:52:9e:5c:2d:7c:7e:06:fb:ce:5c:
         69:8a:c0:7e:69:d0:2f:85:cc:d7:69:69:48:ff:a4:91:42:5e
# openssl x509 -inform der -in ekcert-rsa.der -out ekcert.pem
# openssl verify -verbose -CAfile /var/lib/swtpm-localca/bundle.pem ekcert.pem 
ekcert.pem: OK
```

**Comment by kkaarreell** [comment]
The test should be ready now. However, it is failing
1. due to issue https://github.com/keylime/keylime/issues/1080
2. due to issue https://github.com/keylime/keylime/issues/1070 (this is the one we wanted to reproduce/test)

**Comment by kkaarreell** [comment]
This is now blocked by the missing fix for the actual keylime issue.

**Comment by kkaarreell** [comment]
This is now passing with upstream keylime thanks to https://github.com/keylime/keylime/pull/1156
I am going to merge it.

**Review by sergio-correia — APPROVED** [review]

**Pull request merged**
