### PR TITLE
Allow (temporarily) exit codes 0 and 1 for `regstatus`, `cvstatus` and `add` (with incorrect PCR banks)

### PR DESCRIPTION
**Pull request by maugustosilva**
Related to https://github.com/keylime/keylime/pull/1414

### CODE REVIEW

**Comment by maugustosilva** [comment]
@kkaarreell @ansasaki Looks like a "cascading failure" starting at the `install_upstream_rust_keylime`

```
For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
:: [ 20:06:13 ] :: [   FAIL   ] :: Command 'RUSTFLAGS='-Cinstrument-coverage' cargo build' (Expected 0, got 101)
:: [ 20:06:13 ] :: [  BEGIN   ] :: Running 'make install'
cargo build --target-dir="target" 
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
   Compiling proc-macro2 v1.0.54
   Compiling quote v1.0.26
   Compiling unicode-ident v1.0.4
   Compiling libc v0.2.142
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.54/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
make: *** [GNUmakefile:26: target/debug/keylime_agent] Error 101
:: [ 20:06:13 ] :: [   FAIL   ] :: Command 'make install' (Expected 0, got 2)
:: [ 20:06:13 ] :: [  BEGIN   ] :: Running 'mkdir -p /etc/keylime/agent.conf.d'
:: [ 20:06:13 ] :: [   PASS   ] :: Command 'mkdir -p /etc/keylime/agent.conf.d' (Expected 0, got 0)
:: [ 20:06:13 ] :: [  BEGIN   ] :: Running 'cat > /etc/keylime/agent.conf.d/tpm_hash_alg.conf <<_EOF

```

**Comment by kkaarreell** [comment]
@maugustosilva I agree. Let's wait a few days to see if @ansasaki makes a progress with the issue.

**Comment by ansasaki** [comment]
Apparently the compilation issue is the same issue as described in https://github.com/rust-lang/rust/issues/113152

This is due to the usage of nightly rust compiler (needed for the test coverage measurement). If I understood the issue correctly, the `proc-macro2` crate used a feature that was removed in the nightly compiler in https://github.com/rust-lang/rust/pull/111571. The issue should be fixed on `proc-macro2 1.0.60+` by https://github.com/dtolnay/proc-macro2/pull/391. 

I'll try to bump the version on rust agent side.

**Review by kkaarreell — APPROVED** [review]

**Pull request merged**
