### PR TITLE
Allow the matching of an error which optionally might include an agent id on tpm_policy test.

### PR DESCRIPTION
**Pull request by maugustosilva**

### CODE REVIEW

**Comment by kkaarreell** [comment]
Thank you. Also functional/measured-boot-swtpm-sanity is failing in the other PR and log message check needs updating.

**Comment by Koncpa** [comment]
I'll tomorrow review it and merge it. @kkaarreell

**Comment by Koncpa** [comment]
LGTM, Merging.

**Comment by kkaarreell** [comment]
@Koncpa this PR was lacking update of one additional tests as there were 2 tests failing due to updated log messages in the keylime PR.

**Comment by Koncpa** [comment]
@kkaarreell  When I look into [keylime CI](https://artifacts.dev.testing-farm.io/649f9e60-c77d-46a4-825c-4712ce870628/) that should be only  `/functional/measured-boot-swtpm-sanity`. I prepared PR for that issue.

**Pull request merged**
